[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # Jangan dibundle, biar require di runtime
  external_node_modules = ["@resvg/resvg-js"]
  # Pastikan file .node yang diperlukan ikut dibawa ke artefak deploy
  included_files = [
    "node_modules/@resvg/resvg-js-*/**/*.node"
  ]
